        /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import model.Auto;

/**
 *
 * @author aldai
 */
public class FrmPrincipal extends ManejadorDeAutos {

    FrmIngresarAuto frmauto = new FrmIngresarAuto();
    FrmListarAutos frmlistar = new FrmListarAutos();
    FrmBorrar frmbor = new FrmBorrar();
    FrmOrdenarPlaca frmordplaca = new FrmOrdenarPlaca();
    FrmOrdenarValor frmordvalor = new FrmOrdenarValor();
    FrmBuscarPlaca frmbscplaca = new FrmBuscarPlaca();
    FrmBuscarValor frmbuscvalor = new FrmBuscarValor();
    FrmListrarMarca frmlistarmarca = new FrmListrarMarca();

    /**
     * Creates new form frmPrincipal
     */
    public FrmPrincipal() {
        //this.autos = new ArrayList<>();
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMenu = new javax.swing.JLabel();
        btnInsertarAuto = new javax.swing.JButton();
        btnListarAutos = new javax.swing.JButton();
        btnBorrarAutos = new javax.swing.JButton();
        btnOrdenarPlaca = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMenu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMenu.setText("MENÚ");

        btnInsertarAuto.setText("INSERTAR AUTO");
        btnInsertarAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarAutoActionPerformed(evt);
            }
        });

        btnListarAutos.setText("LISTAR AUTOS");
        btnListarAutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarAutosActionPerformed(evt);
            }
        });

        btnBorrarAutos.setText("BORRAR AUTOS");
        btnBorrarAutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarAutosActionPerformed(evt);
            }
        });

        btnOrdenarPlaca.setText("ORDENAR PLACA");
        btnOrdenarPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarPlacaActionPerformed(evt);
            }
        });

        jButton1.setText("ORDENAR VALOR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("BUSCAR PLACA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("BUSCAR VALOR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("LISTAR POR MARCA");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnInsertarAuto)
                        .addGap(18, 18, 18)
                        .addComponent(btnListarAutos)
                        .addGap(18, 18, 18)
                        .addComponent(btnBorrarAutos)
                        .addGap(18, 18, 18)
                        .addComponent(btnOrdenarPlaca))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButton1)
                        .addGap(36, 36, 36)
                        .addComponent(jButton2)
                        .addGap(29, 29, 29)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(lblMenu)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblMenu)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertarAuto)
                    .addComponent(btnListarAutos)
                    .addComponent(btnBorrarAutos)
                    .addComponent(btnOrdenarPlaca))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton1))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarAutoActionPerformed
        
        frmauto.setAutos(getAutos());
        frmauto.setVisible(true);
    }//GEN-LAST:event_btnInsertarAutoActionPerformed

    private void btnListarAutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarAutosActionPerformed
        
        frmlistar.setAutos(getAutos());
        frmlistar.setVisible(true);
    }//GEN-LAST:event_btnListarAutosActionPerformed

    private void btnBorrarAutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarAutosActionPerformed
        
        frmbor.setAutos(getAutos());
        frmbor.setVisible(true);
    }//GEN-LAST:event_btnBorrarAutosActionPerformed

    private void btnOrdenarPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarPlacaActionPerformed
        frmordplaca.setAutos(getAutos());
        frmordplaca.setVisible(true);
    }//GEN-LAST:event_btnOrdenarPlacaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         frmordvalor.setAutos(getAutos());
        frmordvalor.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         frmbscplaca.setAutos(getAutos());
        frmbscplaca.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         frmbuscvalor.setAutos(getAutos());
        frmbuscvalor.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         frmlistarmarca.setAutos(getAutos());
        frmlistarmarca.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarAutos;
    private javax.swing.JButton btnInsertarAuto;
    private javax.swing.JButton btnListarAutos;
    private javax.swing.JButton btnOrdenarPlaca;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel lblMenu;
    // End of variables declaration//GEN-END:variables

    
}
